
services:
  db:
    image: mysql:9.0.1
    cap_add:
      - SYS_NICE
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=dnd
      - MYSQL_ROOT_PASSWORD=123qweasd
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
